import { pbkdf2Sync, randomBytes } from 'node:crypto';
import { xchacha20poly1305 } from '@noble/ciphers/chacha.js';
import { pbkdf2Async } from '@noble/hashes/pbkdf2.js';
import { sha256 } from '@noble/hashes/sha2.js';
import { afterEach, describe, expect, it, vi } from 'vitest';

import {
  getPbkdf2Implementation,
  jsPbkdf2Sha256,
  NATIVE_KNOWN_ANSWERS,
  pbkdf2Sha256,
  setNativePbkdf2ModuleForTesting,
} from '@/crypto/pbkdf2';
import * as crypto from '@/crypto/reflectionEncryption';
import { fakeNativePbkdf2 } from './helpers/nativePbkdf2';

/**
 * The native PBKDF2 module is a computational drop-in: for the same password,
 * salt, iteration count and length it must yield exactly the bytes the
 * original JS implementation (@noble/hashes pbkdf2Async over the password
 * string) yields, so every existing wrapped key and reflection stays readable.
 */

const hex = (bytes: Uint8Array) => Buffer.from(bytes).toString('hex');
const random = (n: number) => new Uint8Array(randomBytes(n));

/** The implementation as it was before the native module: the reference every path must match. */
const referenceDerive = (password: string, salt: Uint8Array, iterations: number, dkLen = 32) =>
  pbkdf2Async(sha256, password, salt, { c: iterations, dkLen });

/**
 * Generated by the pre-native implementation (noble pbkdf2Async +
 * XChaCha20-Poly1305) with fixed salts/nonces at the production 210,000
 * iterations, standing in for data already stored on users' devices/servers.
 */
const FIXTURE = {
  masterKey: 'ByRBXnuYtdLvDClGY4Cdutf0ES5LaIWiv9z5FjNQbYo=',
  v2Password: 'صبر جميل · Patience 🌙',
  v2: { wrappedKey: 'DG0vxq/cHseYg08MGzWLWSyEJ7vHVp//1fyF6kNt7CbrG+2MzXpmcRme44JWdr9J', nonce: 'DClGY4Cdutf0ES5LaIWiv9z5FjNQbYqn', salt: 'CyhFYn+cudbzEC1KZ4Shvg==', kdfIterations: 210000, encryptionVersion: 2 },
  v1Password: 'ﬁle Ｐassword', // wrapped NFKC-normalized ("file Password"), as version 1 did
  v1: { wrappedKey: 'veMeK0HAkDYKIihVvIHzT+JuDilhwTwSwebJOEjyU6PjbG+IFIIYOVg72c/Ubjzy', nonce: 'NFFui6jF4v8cOVZzkK3K5wQhPlt4lbLP', salt: 'M1BtiqfE4f4bOFVyj6zJ5g==', kdfIterations: 210000, encryptionVersion: 1 },
  reflection: { ciphertext: 'MtTQfUCFQXe7SAtnew7syu+IgzDqaOQLIYuu8ODNR1Se1Jtbd3zOe4rpi4otEoRcXTPS1OsxaVAOP9UPgfeOeBOygc8zmNfr', nonce: 'Y4Cdutf0ES5LaIWiv9z5FjNQbYqnxOH+', encryptionVersion: 1 },
  reflectionText: 'إن مع العسر يسرا — an existing reflection',
};

const PASSWORD_FIXTURES = [
  'correct horse battery staple',
  'صبر جميل',
  'ﬁle Ｐassword', // NFKC-sensitive: must NOT be normalized by the KDF itself
  'emoji 🌙✨ and ZWJ 👩‍👩‍👧',
  'lone surrogate \uD800 here', // TextEncoder maps it to U+FFFD on both paths
  ' leading and trailing spaces ',
  'x'.repeat(200),
  // Boundaries of the 8–32 code point rule (utils/syncPasswordValidation.ts) and symbols.
  `!@#$%^&*`,
  'p@ss w0rd ~`\'"\\|<>',
  '🌙'.repeat(32), // 32 code points, 64 UTF-16 units, 128 UTF-8 bytes
  'كلمةسرّ١',
  'Tab\tand\nnewline',
];

afterEach(() => setNativePbkdf2ModuleForTesting(undefined));

describe('parameters are unchanged', () => {
  it('keeps PBKDF2-HMAC-SHA256, 210,000 iterations, 32-byte keys, 16-byte salts and both key versions', () => {
    expect(crypto.DEFAULT_KDF_ITERATIONS).toBe(210_000);
    expect(crypto.MASTER_KEY_LENGTH_BYTES).toBe(32);
    expect(crypto.SALT_LENGTH_BYTES).toBe(16);
    expect(crypto.NONCE_LENGTH_BYTES).toBe(24);
    expect(crypto.SYNC_KEY_VERSION).toBe(2);
    expect(crypto.ENCRYPTION_VERSION).toBe(1);
  });

  it('wraps with the default iteration count', async () => {
    setNativePbkdf2ModuleForTesting(fakeNativePbkdf2());
    const wrapped = await crypto.wrapMasterKey(random(32), 'a password', random);
    expect(wrapped.kdfIterations).toBe(210_000);
    expect(wrapped.encryptionVersion).toBe(2);
  });
});

describe('known-answer vectors', () => {
  it.each(NATIVE_KNOWN_ANSWERS)('OpenSSL and the JS implementation both produce the on-device known answer (%#)', async (vector) => {
    const password = Buffer.from(vector.password, 'base64');
    const salt = Buffer.from(vector.salt, 'base64');
    expect(pbkdf2Sync(password, salt, vector.iterations, vector.keyLength, 'sha256').toString('base64')).toBe(vector.expected);
    expect(Buffer.from(await jsPbkdf2Sha256(password, salt, vector.iterations, vector.keyLength)).toString('base64')).toBe(vector.expected);
  });

  it('the first vector is RFC 7914 §11 (PBKDF2-HMAC-SHA256, "passwd"/"salt", c=1, 64 bytes)', () => {
    expect(Buffer.from(NATIVE_KNOWN_ANSWERS[0].expected, 'base64').toString('hex')).toBe(
      '55ac046e56e3089fec1691c22544b605f94185216dde0465e68b9d57c20dacbc49ca9cccf179b645991664b39d77ef317c71b845b1e30bd509112041d3a19783',
    );
  });
});

describe('native and JS derive byte-identical keys', () => {
  it.each(PASSWORD_FIXTURES)('%s', async (password) => {
    const salt = random(16);
    const reference = hex(await referenceDerive(password, salt, 2000));

    setNativePbkdf2ModuleForTesting(fakeNativePbkdf2());
    expect(await getPbkdf2Implementation()).toBe('native');
    expect(hex(await pbkdf2Sha256(password, salt, 2000, 32))).toBe(reference);

    setNativePbkdf2ModuleForTesting(null);
    expect(await getPbkdf2Implementation()).toBe('js');
    expect(hex(await pbkdf2Sha256(password, salt, 2000, 32))).toBe(reference);
  });

  it('at the production 210,000 iterations', { timeout: 30_000 }, async () => {
    const salt = random(16);
    const reference = hex(await referenceDerive('a real sync password', salt, 210_000));
    const native = fakeNativePbkdf2();
    setNativePbkdf2ModuleForTesting(native);
    expect(hex(await crypto.derivePassphraseKey('a real sync password', salt))).toBe(reference);
    expect(native.calls.at(-1)).toEqual({ iterations: 210_000, keyLength: 32 });
  });
});

describe('existing encrypted data stays readable', { timeout: 30_000 }, () => {
  const masterKey = () => Uint8Array.from(Buffer.from(FIXTURE.masterKey, 'base64'));

  it.each(['native', 'js'] as const)('a version-2 wrapped key and its reflection decrypt (%s)', async (mode) => {
    setNativePbkdf2ModuleForTesting(mode === 'native' ? fakeNativePbkdf2() : null);
    const key = await crypto.unwrapMasterKey(FIXTURE.v2, FIXTURE.v2Password);
    expect(hex(key)).toBe(hex(masterKey()));
    expect(crypto.decryptReflectionText(FIXTURE.reflection, key)).toBe(FIXTURE.reflectionText);
    await expect(crypto.unwrapMasterKey(FIXTURE.v2, 'wrong password')).rejects.toThrow();
  });

  it.each(['native', 'js'] as const)('a legacy version-1 wrapped key still unlocks with or without NFKC (%s)', async (mode) => {
    setNativePbkdf2ModuleForTesting(mode === 'native' ? fakeNativePbkdf2() : null);
    expect(hex(await crypto.unwrapMasterKey(FIXTURE.v1, FIXTURE.v1Password))).toBe(hex(masterKey()));
    expect(hex(await crypto.unwrapMasterKey(FIXTURE.v1, 'file Password'))).toBe(hex(masterKey()));
  });

  it('a key wrapped through the native path is readable by the reference JS implementation', async () => {
    setNativePbkdf2ModuleForTesting(fakeNativePbkdf2());
    const key = random(32);
    const wrapped = await crypto.wrapMasterKey(key, 'ﬁle Ｐassword 🌙', random, 5000);
    const derived = await referenceDerive('ﬁle Ｐassword 🌙', Buffer.from(wrapped.salt, 'base64'), 5000);
    const unwrapped = xchacha20poly1305(derived, Buffer.from(wrapped.nonce, 'base64')).decrypt(Buffer.from(wrapped.wrappedKey, 'base64'));
    expect(hex(unwrapped)).toBe(hex(key));
  });
});

describe('password length rule and the KDF', () => {
  it('the boundary fixtures are exactly the allowed minimum and maximum lengths', async () => {
    const { passwordLengthError } = await import('@/utils/syncPasswordValidation');
    expect(passwordLengthError('!@#$%^&*')).toBeNull();
    expect(passwordLengthError('🌙'.repeat(32))).toBeNull();
    expect(passwordLengthError('🌙'.repeat(33))).toBe('tooLong');
    expect(passwordLengthError('1234567')).toBe('tooShort');
  });

  it('passwords differing only in spaces or normalization derive different keys (version 2 uses exact input)', async () => {
    const salt = random(16);
    const keys = await Promise.all(['pass word', 'password', 'pass  word', 'ﬁle Ｐassword', 'file Password'].map(async (p) => hex(await pbkdf2Sha256(p, salt, 1000, 32))));
    expect(new Set(keys).size).toBe(keys.length);
  });
});

describe('per-key work factor (D8)', () => {
  it('unwraps each key with its own stored iteration count, so a future default never affects existing keys', async () => {
    const key = random(32);
    const older = await crypto.wrapMasterKey(key, 'same password', random, 3000);
    const newer = await crypto.wrapMasterKey(key, 'same password', random, 7000);
    expect([older.kdfIterations, newer.kdfIterations]).toEqual([3000, 7000]);

    for (const mode of ['native', 'js'] as const) {
      const native = fakeNativePbkdf2();
      setNativePbkdf2ModuleForTesting(mode === 'native' ? native : null);
      expect(hex(await crypto.unwrapMasterKey(older, 'same password'))).toBe(hex(key));
      expect(hex(await crypto.unwrapMasterKey(newer, 'same password'))).toBe(hex(key));
      if (mode === 'native') expect(native.calls.slice(-2).map((call) => call.iterations)).toEqual([3000, 7000]);
    }
  });

  it('a key whose stored iteration count was altered no longer unwraps (the count is part of what the password protects)', async () => {
    const wrapped = await crypto.wrapMasterKey(random(32), 'a password', random, 3000);
    await expect(crypto.unwrapMasterKey({ ...wrapped, kdfIterations: 3001 }, 'a password')).rejects.toThrow();
  });

  it('records exactly the iteration count it used', async () => {
    const wrapped = await crypto.wrapMasterKey(random(32), 'a password', random, 4321);
    const derived = await referenceDerive('a password', Buffer.from(wrapped.salt, 'base64'), 4321);
    expect(() => xchacha20poly1305(derived, Buffer.from(wrapped.nonce, 'base64')).decrypt(Buffer.from(wrapped.wrappedKey, 'base64'))).not.toThrow();
  });
});

describe('fallback to the JS implementation', () => {
  it('runs the known-answer test once, shared by concurrent derivations', async () => {
    const native = fakeNativePbkdf2();
    setNativePbkdf2ModuleForTesting(native);
    const salt = random(16);
    await Promise.all([pbkdf2Sha256('a', salt, 100, 32), pbkdf2Sha256('b', salt, 100, 32)]);
    await pbkdf2Sha256('c', salt, 100, 32);
    expect(native.calls.length).toBe(NATIVE_KNOWN_ANSWERS.length + 3);
  });

  it('a module that fails the known-answer test is never used for real derivations', async () => {
    const native = fakeNativePbkdf2();
    const wrong = { ...native, pbkdf2Sha256: vi.fn(async (...args: Parameters<typeof native.pbkdf2Sha256>) => (await native.pbkdf2Sha256(...args)).replace(/^./, (c) => (c === 'A' ? 'B' : 'A'))) };
    setNativePbkdf2ModuleForTesting(wrong);
    const salt = random(16);
    expect(await getPbkdf2Implementation()).toBe('js');
    const callsAfterCheck = wrong.pbkdf2Sha256.mock.calls.length;
    expect(hex(await pbkdf2Sha256('a password', salt, 1000, 32))).toBe(hex(await referenceDerive('a password', salt, 1000)));
    expect(wrong.pbkdf2Sha256.mock.calls.length).toBe(callsAfterCheck);
  });

  it('a module that throws during the known-answer test falls back to JS', async () => {
    setNativePbkdf2ModuleForTesting({ pbkdf2Sha256: async () => { throw new Error('not linked'); } });
    expect(await getPbkdf2Implementation()).toBe('js');
  });

  it('a native error or a wrong-length result on a real derivation falls back to JS with the same bytes', async () => {
    const native = fakeNativePbkdf2();
    let mode: 'ok' | 'throw' | 'short' = 'ok';
    setNativePbkdf2ModuleForTesting({
      pbkdf2Sha256: async (...args: Parameters<typeof native.pbkdf2Sha256>) => {
        if (mode === 'throw') throw new Error('native crash');
        if (mode === 'short') return Buffer.alloc(16).toString('base64');
        return native.pbkdf2Sha256(...args);
      },
    });
    const salt = random(16);
    const reference = hex(await referenceDerive('a password', salt, 1000));
    await getPbkdf2Implementation();
    mode = 'throw';
    expect(hex(await pbkdf2Sha256('a password', salt, 1000, 32))).toBe(reference);
    mode = 'short';
    expect(hex(await pbkdf2Sha256('a password', salt, 1000, 32))).toBe(reference);
  });

  it('a wrong password still fails to unwrap when native is unavailable mid-unlock', { timeout: 30_000 }, async () => {
    setNativePbkdf2ModuleForTesting({ pbkdf2Sha256: async () => { throw new Error('gone'); } });
    await expect(crypto.unwrapMasterKey(FIXTURE.v2, 'wrong password')).rejects.toThrow();
  });
});
