import type { SeedEmotion } from './types';

export const seedEmotions: SeedEmotion[] = [
  {
    key: 'sad',
    name: 'Sad',
    arabicName: 'حزين',
    description: 'When your heart feels heavy.',
    icon: 'cloud-rain',
    order: 1,
    active: true,
  },
  {
    key: 'anxious',
    name: 'Anxious',
    arabicName: 'قلق',
    description: 'When thoughts feel restless.',
    icon: 'activity',
    order: 2,
    active: true,
  },
  {
    key: 'lonely',
    name: 'Lonely',
    arabicName: 'وحيد',
    description: 'When you feel unseen or alone.',
    icon: 'moon',
    order: 3,
    active: true,
  },
  {
    key: 'angry',
    name: 'Angry',
    arabicName: 'غاضب',
    description: 'When emotion rises quickly.',
    icon: 'flame',
    order: 4,
    active: true,
  },
  {
    key: 'lost',
    name: 'Lost',
    arabicName: 'تائه',
    description: 'When the next step feels unclear.',
    icon: 'compass',
    order: 5,
    active: true,
  },
  {
    key: 'afraid',
    name: 'Afraid',
    arabicName: 'خائف',
    description: 'When fear is close.',
    icon: 'shield-alert',
    order: 6,
    active: true,
  },
  {
    key: 'stressed',
    name: 'Stressed',
    arabicName: 'متوتر',
    description: 'When pressure feels too much.',
    icon: 'gauge',
    order: 7,
    active: true,
  },
  {
    key: 'hopeless',
    name: 'Hopeless',
    arabicName: 'فاقد الأمل',
    description: 'When mercy feels far away.',
    icon: 'sunrise',
    order: 8,
    active: true,
  },
  {
    key: 'tired',
    name: 'Tired',
    arabicName: 'متعب',
    description: 'When your strength feels thin.',
    icon: 'battery-low',
    order: 9,
    active: true,
  },
  {
    key: 'confused',
    name: 'Confused',
    arabicName: 'حائر',
    description: 'When your heart seeks direction.',
    icon: 'help-circle',
    order: 10,
    active: true,
  },
  {
    key: 'grateful',
    name: 'Grateful',
    arabicName: 'ممتن',
    description: 'When you want to name the blessing.',
    icon: 'heart',
    order: 11,
    active: true,
  },
  {
    key: 'peaceful',
    name: 'Peaceful',
    arabicName: 'مطمئن',
    description: 'When your heart feels settled.',
    icon: 'leaf',
    order: 12,
    active: true,
  },
];

