import type { SeedEmotion } from './types';

export const seedEmotions: SeedEmotion[] = [
  {
    key: 'sad',
    name: 'Sad',
    arabicName: 'حزين',
    description: 'When your heart feels heavy.',
    icon: 'cloud-rain',
    order: 1,
    active: true,
  },
  {
    key: 'anxious',
    name: 'Anxious',
    arabicName: 'قلق',
    description: 'When thoughts feel restless.',
    icon: 'activity',
    order: 2,
    active: true,
  },
  {
    key: 'lonely',
    name: 'Lonely',
    arabicName: 'وحيد',
    description: 'When you feel unseen or alone.',
    icon: 'moon',
    order: 3,
    active: true,
  },
  {
    key: 'angry',
    name: 'Angry',
    arabicName: 'غاضب',
    description: 'When emotion rises quickly.',
    icon: 'flame',
    order: 4,
    active: true,
  },
  {
    key: 'lost',
    name: 'Lost',
    arabicName: 'تائه',
    description: 'When the next step feels unclear.',
    icon: 'compass',
    order: 5,
    active: true,
  },
  {
    key: 'afraid',
    name: 'Afraid',
    arabicName: 'خائف',
    description: 'When fear is close.',
    icon: 'shield-alert',
    order: 6,
    active: true,
  },
  {
    key: 'stressed',
    name: 'Stressed',
    arabicName: 'متوتر',
    description: 'When pressure feels too much.',
    icon: 'gauge',
    order: 7,
    active: true,
  },
  {
    key: 'hopeless',
    name: 'Hopeless',
    arabicName: 'فاقد الأمل',
    description: 'When mercy feels far away.',
    icon: 'sunrise',
    order: 8,
    active: true,
  },
  {
    key: 'tired',
    name: 'Tired',
    arabicName: 'متعب',
    description: 'When your strength feels thin.',
    icon: 'battery-low',
    order: 9,
    active: true,
  },
  {
    key: 'confused',
    name: 'Confused',
    arabicName: 'حائر',
    description: 'When your heart seeks direction.',
    icon: 'help-circle',
    order: 10,
    active: true,
  },
  {
    key: 'grateful',
    name: 'Grateful',
    arabicName: 'ممتن',
    description: 'When you want to name the blessing.',
    icon: 'heart',
    order: 11,
    active: true,
  },
  {
    key: 'peaceful',
    name: 'Peaceful',
    arabicName: 'مطمئن',
    description: 'When your heart feels settled.',
    icon: 'leaf',
    order: 12,
    active: true,
  },
  // Phase 5B taxonomy — approved MAIN emotions, added INACTIVE.
  // These are not user-visible and receive no Quran mappings in this step.
  // Each becomes `active: true` only once it has at least one approved mapping.
  // `frustrated` and `regretful` are deliberately absent: they resolve through
  // aliases to `angry` and `guilty`. `quran_message` is a separate discovery
  // mode, not an emotion, so it is not seeded here.
  {
    key: 'want_to_cry',
    name: 'I Want to Cry',
    arabicName: 'عايز أعيط',
    description: 'When the tears are close to the surface.',
    icon: 'droplet',
    order: 13,
    active: false,
  },
  {
    key: 'heartbroken',
    name: 'Heartbroken',
    arabicName: 'مكسور الخاطر',
    description: 'When a loss has broken something inside.',
    icon: 'heart-crack',
    order: 14,
    active: false,
  },
  {
    key: 'overwhelmed',
    name: 'Overwhelmed',
    arabicName: 'مخنوق',
    description: 'When everything at once is too much to carry.',
    icon: 'waves',
    order: 15,
    active: false,
  },
  {
    key: 'rejected',
    name: 'Rejected',
    arabicName: 'حاسس إني مرفوض',
    description: 'When you feel pushed away or unwanted.',
    icon: 'user-x',
    order: 16,
    active: false,
  },
  {
    key: 'betrayed',
    name: 'Betrayed',
    arabicName: 'مخذول',
    description: 'When someone you trusted let you down.',
    icon: 'user-minus',
    order: 17,
    active: false,
  },
  {
    key: 'wronged',
    name: 'Wronged',
    arabicName: 'مظلوم',
    description: 'When you have been treated unjustly.',
    icon: 'scale',
    order: 18,
    active: false,
  },
  {
    key: 'forgiveness_struggle',
    name: "I Can't Forgive",
    arabicName: 'مش قادر أسامح',
    description: 'When you cannot yet let go of a hurt.',
    icon: 'unlink',
    order: 19,
    active: false,
  },
  {
    key: 'guilty',
    name: 'Guilty',
    arabicName: 'حاسس بالذنب',
    description: 'When your conscience weighs on you.',
    icon: 'alert-circle',
    order: 20,
    active: false,
  },
  {
    key: 'repentant',
    name: 'I Want to Repent',
    arabicName: 'عايز أتوب',
    description: 'When you want to turn back to Allah.',
    icon: 'rotate-ccw',
    order: 21,
    active: false,
  },
  {
    key: 'weak',
    name: 'Feeling Weak',
    arabicName: 'حاسس إني ضعيف',
    description: 'When you feel you have no strength left.',
    icon: 'battery-warning',
    order: 22,
    active: false,
  },
  {
    key: 'reassurance',
    name: 'I Need Reassurance',
    arabicName: 'محتاج أطمّن',
    description: 'When you need your heart to be settled.',
    icon: 'hand-heart',
    order: 23,
    active: false,
  },
  {
    key: 'patience',
    name: 'I Need Patience',
    arabicName: 'محتاج صبر',
    description: 'When you are asking for the strength to endure.',
    icon: 'hourglass',
    order: 24,
    active: false,
  },
  {
    key: 'strength',
    name: 'I Need Strength',
    arabicName: 'محتاج قوة',
    description: 'When you need to be carried through.',
    icon: 'anchor',
    order: 25,
    active: false,
  },
  {
    key: 'hopeful',
    name: 'Hopeful',
    arabicName: 'عندي أمل',
    description: 'When you can feel the good that is coming.',
    icon: 'sun',
    order: 26,
    active: false,
  },
  {
    key: 'content',
    name: 'Content',
    arabicName: 'راضي / قانع',
    description: 'When your heart accepts what Allah has given.',
    icon: 'smile',
    order: 27,
    active: false,
  },
  {
    key: 'seeking_guidance',
    name: 'Seeking Guidance',
    arabicName: 'محتاج هداية',
    description: 'When you need to be shown the way.',
    icon: 'map',
    order: 28,
    active: false,
  },
  {
    key: 'closer_to_allah',
    name: 'I Want to Be Closer to Allah',
    arabicName: 'عايز أقرب من ربنا',
    description: 'When you want to draw nearer to your Lord.',
    icon: 'sparkles',
    order: 29,
    active: false,
  },
];

